[package]
name = "flashy"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.3"
egui = "0.32.3"
egui_extras = "0.32.3"
serde = "1.0.219"
tokio = { version = "1.47.1", features = ["full"] }
poll-promise = { version = "0.3.0", features = ["tokio"] }
